### ISSUE TITLE
不起作用啊

### ISSUE THREAD

**Issue by dapao9999** [cachefiles/dnsfix#1]
1. 跑了客户端还需要添加搜索后缀吗？要不要把DNS修改为127.0.0.1？
![2017-02-20_133539](https://cloud.githubusercontent.com/assets/6910161/23113241/ce206618-f771-11e6-9ca2-e438651bafb0.png)
2. 自建的话 dnstxrelay.conf是以server端为准，还是以client为准啊，两边都有这个配置文件

**Comment by pagxir** [comment]
跑客户端之后，只需要修改 DNS 为 127.0.0.1，(如果客户端是跑着openwrt的路由器上的话，则为路由器的IP，比如192.168.1.1)。不用增加后缀，因为客户端会通过 -c p.yiz.me 知道如何添加后缀了。

你可以试试 nslookup  www.google.com 127.0.0.1   返回结果是否正确。

至于配置文件，客户端可以跟服务端共用一个配置，不过需要改 nameserver 开头的行，分别改为客户端的ISP 的 DNS，  服务端服务商提供的DNS（比如8.8.8.8).

openwrt 版本可以自助编译:
https://www.cachefiles.net/dnsfix.html

自助编译生成的文件在这里
http://usr.oigle.cc/downloads/dnsfix-openwrt/
